[[main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 1

[[main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 2

[[main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 3

[[main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 4
