baseURL = "https://wguDataNinja.github.io/buddyowens-site/"
theme = "PaperMod"

# URL handling: let Hugo handle paths
# relativeURLs = true
# canonifyURLs = true

[pagination]
  pagerSize = 5

[params]
  env = "production"
  mainSections = ["posts"]
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true
  disableSpecial1stPost = true

[params.homeInfoParams]
  Title = "Welcome"
  Content = """
  I'm Buddy Owens. This is my data science portfolio.

  - See **Posts** for projects
  - Browse **Tags** for topics
  - Try **Search** to explore
  """

[params.cover]
  hidden = false
  hiddenInList = false
  hiddenInSingle = false
  responsiveImages = true

[params.profileMode]
  enabled = false

[[params.social]]
  name = "github"
  url = "https://github.com/YOUR_USERNAME"

[[params.social]]
  name = "linkedin"
  url = "https://linkedin.com/in/YOUR_HANDLE"

[taxonomies]
  tag = "tags"
  series = "series"