baseURL = "https://wgudataninja.github.io/buddyowens-site/"
theme = "PaperMod"

# optional for safer linking on Pages
relativeURLs = true
canonifyURLs = true

[params]
  env = "production"
  mainSections = ["posts"]

  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true
  disableSpecial1stPost = true  # keep the “featured” first post if you like

[params.homeInfoParams]
Title = "Welcome"
Content = """
I'm Buddy Owens. This is my data science portfolio.

- See **Posts** for projects
- Browse **Tags** for topics
- Try **Search** to explore
"""

[params.cover]
  hidden = false
  hiddenInList = false
  hiddenInSingle = false
  responsiveImages = true

# hugo.toml
[params.profileMode]
enabled = false

[[params.social]]
  name = "github"
  url = "https://github.com/YOUR_USERNAME"

[[params.social]]
  name = "linkedin"
  url = "https://linkedin.com/in/YOUR_HANDLE"

[taxonomies]
  tag = "tags"
  series = "series"

paginate = 5
