name: Deploy Hugo to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      # Force the exact Hugo version required by PaperMod
      - name: Install Hugo 0.149.1 (manual)
        run: |
          VER=0.149.1
          curl -sL https://github.com/gohugoio/hugo/releases/download/v${VER}/hugo_extended_${VER}_Linux-64bit.tar.gz -o hugo.tgz
          tar -xzf hugo.tgz hugo
          sudo mv hugo /usr/local/bin/hugo
          hugo version

      - name: Verify submodules
        run: |
          git config --file .gitmodules --list || true
          git submodule status || true
          ls -la themes/PaperMod || true

      - name: Build
        run: hugo --minify

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4